In [1]:
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

import torchinfo
import my

In [2]:
df = pd.read_csv('./ai_job_market.csv')
df


job_id                   company_name    industry  \
0          1                Foster and Sons  Healthcare   
1          2        Boyd, Myers and Ramirez        Tech   
2          3                       King Inc        Tech   
3          4       Cooper, Archer and Lynch        Tech   
4          5                       Hall LLC     Finance   
...      ...                            ...         ...   
1995    1996       Mueller, Ellis and Clark     Finance   
1996    1997                     Roberts-Yu  Automotive   
1997    1998  Brooks, Williams and Randolph   Education   
1998    1999                Castaneda-Smith   Education   
1999    2000                    Estes Group     Finance   

                     job_title  \
0                 Data Analyst   
1     Computer Vision Engineer   
2             Quant Researcher   
3           AI Product Manager   
4               Data Scientist   
...                        ...   
1995              NLP Engineer   
1996        AI Product Manager   
1997              Data Analyst   
1998          Quant Researcher   
1999          Quant Researcher   

                                        skills_required experience_level  \
0     NumPy, Reinforcement Learning, PyTorch, Scikit...              Mid   
1                       Scikit-learn, CUDA, SQL, Pandas           Senior   
2             MLflow, FastAPI, Azure, PyTorch, SQL, GCP            Entry   
3          Scikit-learn, C++, Pandas, LangChain, AWS, R              Mid   
4                       Excel, Keras, SQL, Hugging Face           Senior   
...                                                 ...              ...   
1995                           Flask, FastAPI, Power BI           Senior   
1996           R, Flask, Excel, C++, CUDA, Scikit-learn              Mid   
1997       Hugging Face, Excel, Scikit-learn, R, MLflow            Entry   
1998                          AWS, Python, Scikit-learn           Senior   
1999                        Flask, TensorFlow, Power BI           Senior   

     employment_type                location salary_range_usd posted_date  \
0          Full-time           Tracybury, AR     92860-109598  2025-08-20   
1          Full-time          Lake Scott, CU     78523-144875  2024-03-22   
2          Full-time          East Paige, CM    124496-217204  2025-09-18   
3          Full-time           Perezview, FI     50908-123743  2024-05-08   
4           Contract   North Desireeland, NE     98694-135413  2025-02-24   
...              ...                     ...              ...         ...   
1995      Internship     Washingtonmouth, SD     90382-110126  2024-04-22   
1996          Remote          Joshuafort, ZA     47848-137195  2023-12-02   
1997        Contract  West Brittanyburgh, CG    134994-180108  2023-10-29   
1998        Contract        Anthonyshire, OM      62388-82539  2024-08-10   
1999       Full-time        Benjaminview, NE      55835-97374  2025-02-20   

     company_size                  tools_preferred  
0           Large                  KDB+, LangChain  
1           Large        FastAPI, KDB+, TensorFlow  
2           Large  BigQuery, PyTorch, Scikit-learn  
3           Large     TensorFlow, BigQuery, MLflow  
4           Large               PyTorch, LangChain  
...           ...                              ...  
1995        Large                           MLflow  
1996        Large          KDB+, LangChain, MLflow  
1997        Large                          PyTorch  
1998        Large      MLflow, TensorFlow, FastAPI  
1999      Startup                           MLflow  

[2000 rows x 12 columns]

In [3]:

df['salary_range_usd']
df[['Min_Salary', 'Max_Salary']] = df['salary_range_usd'].str.split('-', expand=True)
df['Min_Salary'] = pd.to_numeric(df['Min_Salary'], errors='coerce')
df['Max_Salary'] = pd.to_numeric(df['Max_Salary'], errors='coerce')
df['Average_Salary']=((df["Min_Salary"]+df["Max_Salary"])/20000)


skills=df["skills_required"].str.split(',', expand=True)
skills.columns = [f'Skill_{i+1}' for i in range(skills.shape[1])]
tools=df["tools_preferred"].str.split(',', expand=True)
tools.columns = [f'Tools_{i+1}' for i in range(tools.shape[1])]
skills
df['Average_Salary']


0       10.12290
1       11.16990
2       17.08500
3        8.73255
4       11.70535
          ...   
1995    10.02540
1996     9.25215
1997    15.75510
1998     7.24635
1999     7.66045
Name: Average_Salary, Length: 2000, dtype: float64

In [4]:
df_combine={}
df = pd.concat([df, skills,tools], axis=1)
df


job_id                   company_name    industry  \
0          1                Foster and Sons  Healthcare   
1          2        Boyd, Myers and Ramirez        Tech   
2          3                       King Inc        Tech   
3          4       Cooper, Archer and Lynch        Tech   
4          5                       Hall LLC     Finance   
...      ...                            ...         ...   
1995    1996       Mueller, Ellis and Clark     Finance   
1996    1997                     Roberts-Yu  Automotive   
1997    1998  Brooks, Williams and Randolph   Education   
1998    1999                Castaneda-Smith   Education   
1999    2000                    Estes Group     Finance   

                     job_title  \
0                 Data Analyst   
1     Computer Vision Engineer   
2             Quant Researcher   
3           AI Product Manager   
4               Data Scientist   
...                        ...   
1995              NLP Engineer   
1996        AI Product Manager   
1997              Data Analyst   
1998          Quant Researcher   
1999          Quant Researcher   

                                        skills_required experience_level  \
0     NumPy, Reinforcement Learning, PyTorch, Scikit...              Mid   
1                       Scikit-learn, CUDA, SQL, Pandas           Senior   
2             MLflow, FastAPI, Azure, PyTorch, SQL, GCP            Entry   
3          Scikit-learn, C++, Pandas, LangChain, AWS, R              Mid   
4                       Excel, Keras, SQL, Hugging Face           Senior   
...                                                 ...              ...   
1995                           Flask, FastAPI, Power BI           Senior   
1996           R, Flask, Excel, C++, CUDA, Scikit-learn              Mid   
1997       Hugging Face, Excel, Scikit-learn, R, MLflow            Entry   
1998                          AWS, Python, Scikit-learn           Senior   
1999                        Flask, TensorFlow, Power BI           Senior   

     employment_type                location salary_range_usd posted_date  \
0          Full-time           Tracybury, AR     92860-109598  2025-08-20   
1          Full-time          Lake Scott, CU     78523-144875  2024-03-22   
2          Full-time          East Paige, CM    124496-217204  2025-09-18   
3          Full-time           Perezview, FI     50908-123743  2024-05-08   
4           Contract   North Desireeland, NE     98694-135413  2025-02-24   
...              ...                     ...              ...         ...   
1995      Internship     Washingtonmouth, SD     90382-110126  2024-04-22   
1996          Remote          Joshuafort, ZA     47848-137195  2023-12-02   
1997        Contract  West Brittanyburgh, CG    134994-180108  2023-10-29   
1998        Contract        Anthonyshire, OM      62388-82539  2024-08-10   
1999       Full-time        Benjaminview, NE      55835-97374  2025-02-20   

      ... Average_Salary       Skill_1                  Skill_2  \
0     ...       10.12290         NumPy   Reinforcement Learning   
1     ...       11.16990  Scikit-learn                     CUDA   
2     ...       17.08500        MLflow                  FastAPI   
3     ...        8.73255  Scikit-learn                      C++   
4     ...       11.70535         Excel                    Keras   
...   ...            ...           ...                      ...   
1995  ...       10.02540         Flask                  FastAPI   
1996  ...        9.25215             R                    Flask   
1997  ...       15.75510  Hugging Face                    Excel   
1998  ...        7.24635           AWS                   Python   
1999  ...        7.66045         Flask               TensorFlow   

            Skill_3        Skill_4  Skill_5        Skill_6     Tools_1  \
0           PyTorch   Scikit-learn      GCP        FastAPI        KDB+   
1               SQL         Pandas     None           None     FastAPI   
2             Azure    

In [20]:
label1, uniqueValues1= pd.factorize(df['Skill_1'])
label2, uniqueValues2= pd.factorize(df['Skill_2'])
label3, uniqueValues3= pd.factorize(df['Skill_3'])
label4, uniqueValues4= pd.factorize(df['Skill_4'])
label5, uniqueValues5= pd.factorize(df['Skill_5'])
label6, uniqueValues6= pd.factorize(df['Tools_1'])
label7, uniqueValues7= pd.factorize(df['Tools_2'])
label8, uniqueValues8= pd.factorize(df['Tools_3'])
label9, uniqueValues9= pd.factorize(df['location'])
label10, uniqueValues10= pd.factorize(df['employment_type'])
label11, uniqueValues11= pd.factorize(df['job_title'])
label12, uniqueValues12= pd.factorize(df['industry'])
label13, uniqueValues13= pd.factorize(df['company_name'])



In [21]:
targetlabel, targetunique= pd.factorize(df['Average_Salary'])
df['target']=targetlabel
df['target']
targetunique

Index([ 10.1229,  11.1699,   17.085,  8.73255, 11.70535,  13.6675,  7.95845,
         7.2588, 16.13715,  12.2195,
       ...
        16.5924,  11.4291,  5.49335,  19.1729,  10.7884,  10.0254,  9.25215,
        15.7551,  7.24635,  7.66045],
      dtype='float64', length=1992)

In [22]:
df['fskill_1']=label1
df['fskill_2']=label2
df['fskill_3']=label3
df['fskill_4']=label4
df['fskill_5']=label5
df['ftool_1']=label6
df['ftool_2']=label7
df['ftool_3']=label8
df['floc']=label9
df['ftype']=label10
df['ftitle']=label11
df['findustry']=label12
df['fname']=label13


In [23]:
df


job_id                   company_name    industry  \
0          1                Foster and Sons  Healthcare   
1          2        Boyd, Myers and Ramirez        Tech   
2          3                       King Inc        Tech   
3          4       Cooper, Archer and Lynch        Tech   
4          5                       Hall LLC     Finance   
...      ...                            ...         ...   
1995    1996       Mueller, Ellis and Clark     Finance   
1996    1997                     Roberts-Yu  Automotive   
1997    1998  Brooks, Williams and Randolph   Education   
1998    1999                Castaneda-Smith   Education   
1999    2000                    Estes Group     Finance   

                     job_title  \
0                 Data Analyst   
1     Computer Vision Engineer   
2             Quant Researcher   
3           AI Product Manager   
4               Data Scientist   
...                        ...   
1995              NLP Engineer   
1996        AI Product Manager   
1997              Data Analyst   
1998          Quant Researcher   
1999          Quant Researcher   

                                        skills_required experience_level  \
0     NumPy, Reinforcement Learning, PyTorch, Scikit...              Mid   
1                       Scikit-learn, CUDA, SQL, Pandas           Senior   
2             MLflow, FastAPI, Azure, PyTorch, SQL, GCP            Entry   
3          Scikit-learn, C++, Pandas, LangChain, AWS, R              Mid   
4                       Excel, Keras, SQL, Hugging Face           Senior   
...                                                 ...              ...   
1995                           Flask, FastAPI, Power BI           Senior   
1996           R, Flask, Excel, C++, CUDA, Scikit-learn              Mid   
1997       Hugging Face, Excel, Scikit-learn, R, MLflow            Entry   
1998                          AWS, Python, Scikit-learn           Senior   
1999                        Flask, TensorFlow, Power BI           Senior   

     employment_type                location salary_range_usd posted_date  \
0          Full-time           Tracybury, AR     92860-109598  2025-08-20   
1          Full-time          Lake Scott, CU     78523-144875  2024-03-22   
2          Full-time          East Paige, CM    124496-217204  2025-09-18   
3          Full-time           Perezview, FI     50908-123743  2024-05-08   
4           Contract   North Desireeland, NE     98694-135413  2025-02-24   
...              ...                     ...              ...         ...   
1995      Internship     Washingtonmouth, SD     90382-110126  2024-04-22   
1996          Remote          Joshuafort, ZA     47848-137195  2023-12-02   
1997        Contract  West Brittanyburgh, CG    134994-180108  2023-10-29   
1998        Contract        Anthonyshire, OM      62388-82539  2024-08-10   
1999       Full-time        Benjaminview, NE      55835-97374  2025-02-20   

      ... fskill_4 fskill_5  ftool_1  ftool_2  ftool_3  floc ftype ftitle  \
0     ...        0        0        0        0       -1     0     0      0   
1     ...        1       -1        1        1        0     1     0      1   
2     ...        2        1        2        2        1     2     0      2   
3     ...        3        2        3        3        2     3     0      3   
4     ...        4       -1        4        0       -1     4     1      4   
...   ...      ...      ...      ...      ...      ...   ...   ...    ...   
1995  ...       -1       -1        6       -1       -1  1995     3      6   
1996  ...       13       13        0        0        2  1996     2      3   
1997  ...       19        7        4       -1       -1  1997     1      0   
1998  ...       -1       -1        6        4        3  1998     1      2   
1999  ...       -1       -1        6       -1       -1  1999     0      2   

     findustry fname  
0            0     0  
1            1     1  
2            1     2  
3            1     3  
4         

In [24]:

inputs = torch.tensor(df.iloc[:,-13:].values, dtype=torch.float32)
df.iloc[:,-13:]

fskill_1  fskill_2  fskill_3  fskill_4  fskill_5  ftool_1  ftool_2  \
0            0         0         0         0         0        0        0   
1            1         1         1         1        -1        1        1   
2            2         2         2         2         1        2        2   
3            1         3         3         3         2        3        3   
4            3         4         1         4        -1        4        0   
...        ...       ...       ...       ...       ...      ...      ...   
1995        16         2        14        -1        -1        6       -1   
1996        11         6        20        13        13        0        0   
1997         9         5         4        19         7        4       -1   
1998        10        16         4        -1        -1        6        4   
1999        16        20        14        -1        -1        6       -1   

      ftool_3  floc  ftype  ftitle  findustry  fname  
0          -1     0      0       0          0      0  
1           0     1      0       1          1      1  
2           1     2      0       2          1      2  
3           2     3      0       3          1      3  
4          -1     4      1       4          2      4  
...       ...   ...    ...     ...        ...    ...  
1995       -1  1995      3       6          2   1904  
1996        2  1996      2       3          4   1905  
1997       -1  1997      1       0          5   1906  
1998        3  1998      1       2          5   1907  
1999       -1  1999      0       2          2   1908  

[2000 rows x 13 columns]

In [25]:

targets =  torch.tensor(df['Average_Salary'].values, dtype=torch.int64)

targets

tensor([10, 11, 17,  ..., 15,  7,  7])

In [26]:
dataset =  TensorDataset(inputs, targets)

In [27]:
dataset[0]

(tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.]),
 tensor(10))

In [28]:
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

In [29]:
torch.manual_seed(0)
next(iter(dataloader))

[tensor([[ 1.7000e+01,  1.1000e+01,  6.0000e+00, -1.0000e+00, -1.0000e+00,
           7.0000e+00,  3.0000e+00,  2.0000e+00,  1.2260e+03,  2.0000e+00,
           2.0000e+00,  5.0000e+00,  1.1920e+03],
         [ 2.0000e+00,  1.6000e+01,  7.0000e+00,  3.0000e+00, -1.0000e+00,
           3.0000e+00,  2.0000e+00,  5.0000e+00,  5.0900e+02,  0.0000e+00,
           0.0000e+00,  0.0000e+00,  5.0300e+02],
         [ 9.0000e+00,  2.1000e+01,  1.5000e+01,  0.0000e+00, -1.0000e+00,
           6.0000e+00,  4.0000e+00,  5.0000e+00,  1.6310e+03,  0.0000e+00,
           1.0000e+00,  6.0000e+00,  1.5690e+03],
         [ 2.0000e+00,  6.0000e+00,  1.9000e+01, -1.0000e+00, -1.0000e+00,
           4.0000e+00,  5.0000e+00,  0.0000e+00,  1.1320e+03,  1.0000e+00,
           6.0000e+00,  5.0000e+00,  1.1040e+03]]),
 tensor([11,  7, 13,  5])]

In [30]:
# [THIS IS READ-ONLY]
class LinearClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(13, 3)
    def forward(self, x):
        # x ~ (batch_size, 4)
        return self.fc(x)


In [31]:
torchinfo.summary(LinearClassifier())

Layer (type:depth-idx)                   Param #
LinearClassifier                         --
├─Linear: 1-1                            42
Total params: 42
Trainable params: 42
Non-trainable params: 0

In [32]:
torch.manual_seed(0)
x, targets = next(iter(dataloader))
model = LinearClassifier()
y = model(x)
y

tensor([[-196.0265,  -48.9636,  205.3186],
        [ -78.5724,  -24.0096,   88.7119],
        [-260.0611,  -68.0360,  275.0341],
        [-180.1619,  -49.2741,  187.5451]], grad_fn=<AddmmBackward0>)

In [33]:
import torch.nn.functional as F
def loss_fn(y, targets):
    loss = F.cross_entropy(y, targets)
    return loss

In [34]:
torch.manual_seed(0)
x, targets = next(iter(dataloader))
model = LinearClassifier()
y = model(x)
with torch.no_grad():
    loss = loss_fn(y, targets)
loss

IndexError: Target 11 is out of bounds.

In [ ]:
targets